package com.example.samuel.expensemanager.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig expenseDaoConfig;
    private final DaoConfig typeInfoDaoConfig;

    private final ExpenseDao expenseDao;
    private final TypeInfoDao typeInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        expenseDaoConfig = daoConfigMap.get(ExpenseDao.class).clone();
        expenseDaoConfig.initIdentityScope(type);

        typeInfoDaoConfig = daoConfigMap.get(TypeInfoDao.class).clone();
        typeInfoDaoConfig.initIdentityScope(type);

        expenseDao = new ExpenseDao(expenseDaoConfig, this);
        typeInfoDao = new TypeInfoDao(typeInfoDaoConfig, this);

        registerDao(Expense.class, expenseDao);
        registerDao(TypeInfo.class, typeInfoDao);
    }

    public void clear() {
        expenseDaoConfig.getIdentityScope().clear();
        typeInfoDaoConfig.getIdentityScope().clear();
    }

    public ExpenseDao getExpenseDao() {
        return expenseDao;
    }

    public TypeInfoDao getTypeInfoDao() {
        return typeInfoDao;
    }

}
