package com.example.samuel.expensemanager.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EXPENSE".
 */
public class Expense {

    private Long id;
    private String expenseObjectId;
    private String date;
    private Double figure;
    private String typeName;
    private Integer typeColor;
    private Integer typeFlag;
    private Integer isUploaded;
    private Integer isModified;
    private Integer isDeleted;

    public Expense() {
    }

    public Expense(Long id) {
        this.id = id;
    }

    public Expense(Long id, String expenseObjectId, String date, Double figure, String typeName, Integer typeColor, Integer typeFlag, Integer isUploaded, Integer isModified, Integer isDeleted) {
        this.id = id;
        this.expenseObjectId = expenseObjectId;
        this.date = date;
        this.figure = figure;
        this.typeName = typeName;
        this.typeColor = typeColor;
        this.typeFlag = typeFlag;
        this.isUploaded = isUploaded;
        this.isModified = isModified;
        this.isDeleted = isDeleted;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getExpenseObjectId() {
        return expenseObjectId;
    }

    public void setExpenseObjectId(String expenseObjectId) {
        this.expenseObjectId = expenseObjectId;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Double getFigure() {
        return figure;
    }

    public void setFigure(Double figure) {
        this.figure = figure;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public Integer getTypeColor() {
        return typeColor;
    }

    public void setTypeColor(Integer typeColor) {
        this.typeColor = typeColor;
    }

    public Integer getTypeFlag() {
        return typeFlag;
    }

    public void setTypeFlag(Integer typeFlag) {
        this.typeFlag = typeFlag;
    }

    public Integer getIsUploaded() {
        return isUploaded;
    }

    public void setIsUploaded(Integer isUploaded) {
        this.isUploaded = isUploaded;
    }

    public Integer getIsModified() {
        return isModified;
    }

    public void setIsModified(Integer isModified) {
        this.isModified = isModified;
    }

    public Integer getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

}
