package com.example.samuel.expensemanager.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TYPE_INFO".
 */
public class TypeInfo {

    private Long id;
    private String typeObjectId;
    private Integer typeColor;
    private String typeName;
    private String typeFlag;
    private Integer frequency;
    private Integer isUploaded;
    private Integer isModified;
    private Integer isDeleted;

    public TypeInfo() {
    }

    public TypeInfo(Long id) {
        this.id = id;
    }

    public TypeInfo(Long id, String typeObjectId, Integer typeColor, String typeName, String typeFlag, Integer frequency, Integer isUploaded, Integer isModified, Integer isDeleted) {
        this.id = id;
        this.typeObjectId = typeObjectId;
        this.typeColor = typeColor;
        this.typeName = typeName;
        this.typeFlag = typeFlag;
        this.frequency = frequency;
        this.isUploaded = isUploaded;
        this.isModified = isModified;
        this.isDeleted = isDeleted;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTypeObjectId() {
        return typeObjectId;
    }

    public void setTypeObjectId(String typeObjectId) {
        this.typeObjectId = typeObjectId;
    }

    public Integer getTypeColor() {
        return typeColor;
    }

    public void setTypeColor(Integer typeColor) {
        this.typeColor = typeColor;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public String getTypeFlag() {
        return typeFlag;
    }

    public void setTypeFlag(String typeFlag) {
        this.typeFlag = typeFlag;
    }

    public Integer getFrequency() {
        return frequency;
    }

    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

    public Integer getIsUploaded() {
        return isUploaded;
    }

    public void setIsUploaded(Integer isUploaded) {
        this.isUploaded = isUploaded;
    }

    public Integer getIsModified() {
        return isModified;
    }

    public void setIsModified(Integer isModified) {
        this.isModified = isModified;
    }

    public Integer getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

}
